### ISSUE TITLE
Need to add bidId and saleId in events

### ISSUE THREAD

**Issue by parva-jain** [Pandora-Finance/Modular-contract#15]
There is a need to make small changes in the contract which is to add bidId and sale Id in respective events. This is required in the SDK so that our SDK user can get the necessary information through emitted events.
@vishaldantuluri @techpandora

**Comment by vishaldantuluri** [comment]
dbb9fa02ba38cefb6bf80d3b58b1452a184aa8cb

**Comment by vishaldantuluri** [comment]
@techpandora @parva-jain
