### ISSUE TITLE
TokenURI  issue: Audit report

### ISSUE THREAD

**Issue by techpandora** [Pandora-Finance/Modular-contract#18]
Anyone can call setTokenUri. No access control modifier has been used.
Remediation- Use approapriate access control modifiers such as Openzeppelin onlyOwner or Roles

**Comment by vishaldantuluri** [comment]
1397e2c8c1c4d94b01e19b64177152fda13e71a5

**Comment by vishaldantuluri** [comment]
I have made the function internal @techpandora @parva-jain @kishan79

**Comment by parva-jain** [comment]
Verified the mentioned commit.
setTokenUri function is now internal.
Also ran the new upgradability test and passed successfully.
The issue can be closed @techpandora

**Comment by techpandora** [comment]
@vishaldantuluri we can merge it... with only this issue.
