### ISSUE TITLE
Burn can be called by anyone

### ISSUE THREAD

**Issue by techpandora** [Pandora-Finance/Modular-contract#19]
burn function is vulnerable. Anyone can call this function and burn tokens from any other account.
Remediation- Use approapriate access control modifiers such as Openzeppelin onlyOwner or Roles

**Comment by techpandora** [comment]
Can we check @vishaldantuluri this part with rari and OpenSea

**Comment by vishaldantuluri** [comment]
@techpandora i have changed it to the way rarible is doing it

**Comment by parva-jain** [comment]
#24 follow up on this issue after observing another vulnerability.
This issue can be closed @techpandora
