### ISSUE TITLE
erc1155 burn allows approved addresses

### ISSUE THREAD

**Issue by vishaldantuluri** [Pandora-Finance/Modular-contract#24]
erc1155 burn function is allowing approved addresses to burn tokens.

**Comment by vishaldantuluri** [comment]
039185b4813b256f917087d19c8af2a1c766c552

**Comment by vishaldantuluri** [comment]
@parva-jain @techpandora @kishan79

**Comment by parva-jain** [comment]
Verified the changes.
The issue is good to close.
