### ISSUE TITLE
Audit: NFTFactoryContract For Loop over Dynamic Array

### ISSUE THREAD

**Issue by vishaldantuluri** [Pandora-Finance/Modular-contract#28]
Programming patterns that are harmless in centralized applications can lead to Denial of Service conditions in smart contracts when the cost of executing a function exceeds the block gas limit.

**Comment by techpandora** [comment]
We can put the no of account as 5 for receiving the royalties

**Comment by techpandora** [comment]
Make it upto 10... cc @parva-jain

**Comment by parva-jain** [comment]
Since we added the check at the time of minting that royalties recipients can be almost 10, this issue is solved as iteration can be a maximum of 10 for each nft.
We can close this issue @vishaldantuluri @techpandora @kishan79
