### ISSUE TITLE
Audit: NFTFactoryContract Transfer function used

### ISSUE THREAD

**Issue by vishaldantuluri** [Pandora-Finance/Modular-contract#29]
The transfer() and send() functions forward a fixed amount of 2300 gas. Historically, it has 
often been recommended to use these functions for value transfers to guard against reentrancy attacks. However, the gas cost of EVM instructions may change 
significantly during hard forks which may break already deployed contract systems that make fixed assumptions about gas costs.

**Comment by techpandora** [comment]
testing is required..

**Comment by parva-jain** [comment]
Pr is merged updating transfer/send with call.
We can close this issue @techpandora
