### ISSUE TITLE
Audit: BidContract Missing zero check

### ISSUE THREAD

**Issue by kishan79** [Pandora-Finance/Modular-contract#31]
Missing zero address check for _collectionAddress parameter in the SellNFT_byBid() function.
Also there is missing zero value check for _price and _bidTime parameters in the same
function

**Comment by vishaldantuluri** [comment]
@kishan79 this issue has already been added https://github.com/Pandora-Finance/Modular-contract/issues/25#issue-1139803641

**Comment by parva-jain** [comment]
what should be the threshold for _bidTime?? @techpandora

**Comment by techpandora** [comment]
@parva-jain It should be choose by the person who is putting NFT for bid. Bid time amount can be a input field here

**Comment by vishaldantuluri** [comment]
the missing zero check has already been added into the main branch through a pr, We can close this issue. @parva-jain @kishan79 @techpandora

**Comment by parva-jain** [comment]
@vishaldantuluri missing zero checks for _collectionAddress is merged but audit report says checking _price and _bidTime for zero, so that's y I was asking if we should only check that _bidtime != 0 or we should set a threshold for _bidTime that it needs to be greater than a certain value. @techpandora

**Comment by vishaldantuluri** [comment]
can we do this check on the frontend? @parva-jain

**Comment by parva-jain** [comment]
@vishaldantuluri Yup that can be done on the front end as well. It's on us to check it on our side or put it on client to check.

**Comment by techpandora** [comment]
we can put check on frontend side and make it work..on the dapp
