### ISSUE TITLE
Audit: BidContract External calls made inside a Loop 

### ISSUE THREAD

**Issue by vishaldantuluri** [Pandora-Finance/Modular-contract#33]
In executeBidOrder() there are external calls made inside a loop. This could lead to Denial of Service and out of gas errors.

**Comment by techpandora** [comment]
https://swcregistry.io/docs/SWC-128

**Comment by parva-jain** [comment]
@kishan79 since the maximum number of royalties can be 10, there's no need to add a require statement for checking the max iteration of the loop.
The issue can be closed
