### ISSUE TITLE
Audit: BidContract Transfer and send functions used

### ISSUE THREAD

**Issue by kishan79** [Pandora-Finance/Modular-contract#36]
The transfer() and send() functions forward a fixed amount of 2300 gas. Historically, it has often been recommended to use these functions for value transfers to guard against reentrancy attacks. However, the gas cost of EVM instructions may change significantly during hard forks which may break already deployed contract systems that make fixed assumptions about gas costs

**Comment by parva-jain** [comment]
@kishan79 @vishaldantuluri @techpandora 
#63

**Comment by techpandora** [comment]
@kishan79 please review and share the feedback

**Comment by kishan79** [comment]
Changes verified and merged to main
