### ISSUE TITLE
Audit: Bid1155Contract Transfer and send functions used

### ISSUE THREAD

**Issue by kishan79** [Pandora-Finance/Modular-contract#40]
The transfer() and send() functions forward a fixed amount of 2300 gas. Historically, it has often been recommended to use these functions for value transfers to guard against reentrancy attacks. However, the gas cost of EVM instructions may change significantly during hard forks which may break already deployed contract systems that make fixed assumptions about gas costs.

**Comment by techpandora** [comment]
@parva-jain can we have a look to it

**Comment by parva-jain** [comment]
#77 fixes it
